---
- name: Update Time
  include_tasks: ../tasks/update_time.yaml

- name: Install git
  become: true
  apt:
    name: git
    state: present

- name: Remove EXTERNALLY-MANAGED
  include_tasks: ../tasks/remove-externally-managed.yaml

- name: Clone Mininet
  become: true
  git:
    repo: https://github.com/mininet/mininet
    dest: /opt/mininet
    version: 2.3.1b4

- name: Install Mininet
  become: true
  shell: /opt/mininet/util/install.sh -a
  ignore_errors: true
  register: mininet_install
  changed_when: mininet_install.rc == 0

- name: Run Mininet + OVS test
  become: true
  shell: sudo mn --switch ovsbr --test pingall
  register: mininet_test
  changed_when: false

- name: Show Mininet test output
  debug:
    var: mininet_test.stderr_lines