---
- name: Install NTP
  become: true
  apt:
    name: ntpdate
    state: present

- name: Sync Clock
  become: true
  shell: ntpdate -u 0.fr.pool.ntp.org 1.fr.pool.ntp.org 2.fr.pool.ntp.org 3.fr.pool.ntp.org