- hosts: all

  tasks:
    - name: Include Secrets
      include_vars: vars/tailscale.yaml

    - name: Check if Tailscale is installed
      become: true
      shell: "tailscale status"
      register: tailscale
      ignore_errors: true

    - name: Install Tailscale
      become: true
      when: tailscale is failed
      shell: curl -fsSL https://tailscale.com/install.sh | sh

    - name: Login Tailscale
      become: true
      shell: "tailscale login --login-server https://headscale.ozeliurs.com --auth-key {{ tailscale_auth_key }}"

    - name: Get Tailscale Hostname
      become: true
      shell: "tailscale status --json | jq -r .Self.DNSName"
      register: tailscale_hostname

    - name: Debug Tailscale Hostname
      debug:
        var: tailscale_hostname.stdout
