name: Generate and Commit PDFs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate_and_commit_pdfs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y texlive texlive-latex-extra pandoc

    - name: Generate PDFs
      run: |
        mkdir -p papers/pdfs
        if compgen -G "papers/*.md" > /dev/null; then
          for mdfile in papers/*.md; do
            pdffile="papers/pdfs/$(basename "${mdfile%.md}.pdf")"
            pandoc "$mdfile" --pdf-engine=pdflatex -o "$pdffile"
          done
        else
          echo "No Markdown files found in the papers directory."
        fi

    - name: Get Current Date
      id: date
      run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ steps.date.outputs.date }}
        release_name: Release ${{ steps.date.outputs.date }}
        body: |
          This is the latest version of the PDFs.
          They were generated from the main branch.
        draft: false
        prerelease: false

    - name: Upload Release Assets
      if: success()
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: papers/pdfs/